spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: emt
    password: chinaemt
    url: jdbc:mysql://192.168.1.160:3306/test1?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8


  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect

    show-sql: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

server:
  port: 9065